# Generated by Django 4.2.3 on 2023-08-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restobot_api', '0002_group_dish_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='restobot_api.category'),
        ),
    ]
