# Generated by Django 4.2.4 on 2023-08-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restobot_api', '0002_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
