# Generated by Django 4.2.4 on 2023-09-06 09:40

import django.core.files.storage.filesystem
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restobot_api', '0005_alter_dish_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='picture',
            field=models.ImageField(default='No_image.jpg', storage=django.core.files.storage.filesystem.FileSystemStorage, upload_to=''),
        ),
    ]
