# Generated by Django 4.2.3 on 2023-08-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restobot_api', '0008_order_phone_number_alter_order_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_items',
            new_name='Order_item',
        ),
        migrations.AddField(
            model_name='order',
            name='value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
